### ISSUE TITLE
URL Permalinks Structure

### ISSUE THREAD

**Issue by markusdelbrouck** [better-studio/better-amp#3]
Hi, nice AMP Plugin. You write the Sentence: "Also BetterAMP supports the /amp/ in the end of url to cover "Automatic AMP" plugin urls." How will this be done? Where is the "switch"? I cant find it. 

Thanks for your Answer.

**Comment by aliaghdam** [comment]
Hi dear,

That was done in core of BetterAMP. When you enter or Google uses example.com/post-1/amp/ then BetterAMP redirects that URL to example.com/amp/post-1 to make sure your links are completely ok!

It was done because BetterAMP is complete solution for WP not simple for pages and it creates complete new site for AMP.
